spring.application.name=SIW-GATTILE-01
spring.datasource.url=jdbc:postgresql://localhost:5432/gattile_db
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

server.port=8087

spring.thymeleaf.cache=false